name: Python Tests

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Install dependancies
        run: pip install PyQt5 opencv-python numpy pillow scipy matplotlib pytest

      - name: Run tests
        run: pytest -s test/test_ecosystem.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto PR
          title: Automated PR
          body: Created by a development branch
          branch: main