name: Python Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Install dependancies
        run: pip install PyQt5 opencv-python numpy pillow scipy matplotlib pytest

      - name: Run tests
        run: pytest test/test_ecosystem.py