name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.10.3

      - name: Install dependancies
        run: pip install PyQt5 opencv-python numpy pillow scipy matplotlib

      - name: Run tests
        run: pytest test/test_ecosytem.py
